base_url: https://opendata-ajuntament.barcelona.cat/data

dataset:
  id: 5334c15e-0d70-410b-85f3-d97740ffc1ed
  resource_id: 6f1fb778-0767-478b-b332-c64a833d26d2
  file_name: precipitacionsbarcelonadesde1786.csv
  local_file_path: resources/bcn_rainfall_1786_2022.csv

data:
  start_year: 1971
  rainfall_precision: 2
  kmeans_clusters: 4

api:
  doc_path: src/api/swagger