---
swagger: '2.0'
info:
  title: Barcelona Rainfall API
  description: API to retrieve interesting data in all shapes relative to Barcelona rainfall
  contact:
    responsibleOrganization: PAUL CHARLES
    responsibleDeveloper: Paul Charles
    email: paul.charles@tutanota.com
    url: https://linktr.ee/paul_charles
  termsOfService: https://mit-license.org/
  version: 0.0.1
host: 127.0.0.1:5000
basePath: "/api"
schemes:
- http
operationId: getBcnRainfallData