name: Pylint

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Analyse code with pylint
      run: |
        pylint $(git ls-files src/'*.py' -x src/api/'*.py') --disable import-error,too-many-arguments,no-value-for-parameter
        pylint $(git ls-files src/api/'*.py') --disable import-error,duplicate-code,too-few-public-methods
        pylint $(git ls-files tst/'*.py') --disable import-error,missing-docstring
